apiVersion: v1
kind: Service
metadata:
  name: schedup-server-service
spec:
  ports:
    - port: 80
      targetPort: nest-port
      protocol: TCP
  selector:
    app: schedup-server
  type: LoadBalancer
